//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.15.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Tours Item</summary>
	[PublishedModel("toursItem")]
	public partial class ToursItem : PublishedContentModel, IContentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		public new const string ModelTypeAlias = "toursItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ToursItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ToursItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Description Image 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionImage1")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DescriptionImage1 => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("descriptionImage1");

		///<summary>
		/// Description Image 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionImage2")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DescriptionImage2 => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("descriptionImage2");

		///<summary>
		/// Description Image 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionImage3")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DescriptionImage3 => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("descriptionImage3");

		///<summary>
		/// Description Image 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionImage4")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DescriptionImage4 => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("descriptionImage4");

		///<summary>
		/// Description Text 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionText1")]
		public virtual string DescriptionText1 => this.Value<string>("descriptionText1");

		///<summary>
		/// Description Text 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionText2")]
		public virtual string DescriptionText2 => this.Value<string>("descriptionText2");

		///<summary>
		/// Description Text 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionText3")]
		public virtual string DescriptionText3 => this.Value<string>("descriptionText3");

		///<summary>
		/// Description Text 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("descriptionText4")]
		public virtual string DescriptionText4 => this.Value<string>("descriptionText4");

		///<summary>
		/// How Many Days?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("howManyDays")]
		public virtual int HowManyDays => this.Value<int>("howManyDays");

		///<summary>
		/// How Many Tourists?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("howManyTourists")]
		public virtual int HowManyTourists => this.Value<int>("howManyTourists");

		///<summary>
		/// Pin
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("pin")]
		public virtual bool Pin => this.Value<bool>("pin");

		///<summary>
		/// Price
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("price")]
		public virtual string Price => this.Value<string>("price");

		///<summary>
		/// Short Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("shortContent")]
		public virtual global::System.Web.IHtmlString ShortContent => this.Value<global::System.Web.IHtmlString>("shortContent");

		///<summary>
		/// Start Day
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("startDay")]
		public virtual global::System.DateTime StartDay => this.Value<global::System.DateTime>("startDay");

		///<summary>
		/// Thumbnail Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("thumbnailImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops ThumbnailImage => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("thumbnailImage");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("content")]
		public virtual global::System.Web.IHtmlString Content => global::Umbraco.Web.PublishedModels.ContentBase.GetContent(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Web.PublishedModels.ContentBase.GetPageTitle(this);

		///<summary>
		/// Sub Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.15.0")]
		[ImplementPropertyType("subPageTitle")]
		public virtual string SubPageTitle => global::Umbraco.Web.PublishedModels.ContentBase.GetSubPageTitle(this);
	}
}
